---
# After you have replaced all the __CHANGE_ME__ values in this file, you need to
# run `make auth` to setup the Auth.
tre_id: kpagtre
location: eastus2
management:
  mgmt_resource_group_name: tre-rg
  mgmt_storage_account_name: trestgeu2
  terraform_state_container_name: tfstate
  acr_name: treacreu2
  # Azure Resource Manager credentials used for CI/CD pipelines
  arm_subscription_id: 4d64a3f2-671b-4192-8112-97df403d0ef4
  # If you want to override the currently signed in credentials
  # You would do this if running commands like `make terraform-install DIR=./templates/workspaces/base`
  # arm_tenant_id: __CHANGE_ME__
  # arm_client_id: __CHANGE_ME__
  # arm_client_secret: __CHANGE_ME__
tre:
  # If your local machine/build agent cannot get the public IP
  # address from https://ipecho.net/plain, then you can circumvent
  # this by setting this Environment variable. This blockage can
  # be caused by trying to deploy TRE in an Office environment where
  # this website is blocked. This value is the public facing IP
  # address of the deploying machine.
  # public_deployment_ip_address: __CHANGE_ME__
  core_address_space: 10.0.0.0/22
  tre_address_space: 10.1.0.0/22
  core_app_service_plan_sku: P1v2
  resource_processor_vmss_sku: Standard_B2s
  enable_swagger: true
  enable_airlock_malware_scanning: false
  # TODO: move to RP default with https://github.com/microsoft/AzureTRE/issues/2948
  workspace_app_service_plan_sku: P1v2
  # The TRE Web UI is deployed by default.
  # Uncomment the following to disable deployment of the Web UI.
  # deploy_ui: false
authentication:
  aad_tenant_id: 5000b353-9c2a-48a6-a362-ee4a92282390
  # Setting AUTO_WORKSPACE_APP_REGISTRATION to false will:
  # create an identity with `Application.ReadWrite.OwnedBy`.
  # Setting AUTO_WORKSPACE_APP_REGISTRATION to true will:
  # create an identity with `Application.ReadWrite.All` and `Directory.Read.All`.
  # When this is true, create Workspaces will also create an AAD Application automatically.
  # When this is false, the AAD Application will need creating manually.
  auto_workspace_app_registration: true
  # Setting AUTO_WORKSPACE_GROUP_CREATION to true will create an identity with `Group.ReadWrite.All`
  auto_workspace_group_creation: false
  application_admin_client_id: fdd6b685-160e-4934-b0da-7bfc0f8315a6
  application_admin_client_secret: sMV8Q~aERrChnvwcPWyDSdesX_gLwVgnz8rUcaOB
  test_account_client_id: 569f67c5-e55f-4650-9390-05518e428cbf
  test_account_client_secret: 3vq8Q~4wEUliavbbspmDg3degUQIcOuoelgIIapf
  api_client_id: c8343910-f2f9-4d9a-9bf0-295f5a606885
  api_client_secret: Kak8Q~MHzVXnN4On2XCnhDKveKfvM.5o1Ve9icb8
  swagger_ui_client_id: d086d338-de28-44c5-b42b-1afb85d8a932
resource_processor:
  # The number of processes to start in the resource processor VMSS image
  resource_processor_number_processes_per_instance: 5
# This setting provides a way to pass environment values to the resource processor
# to use as a source of bundle parameter values
# For example, to specify your image_gallery_id for use in VM user resources with custom VM images:
# yamllint disable-line rule:line-length
#   rp_bundle_values: {"image_gallery_id":"/subscriptions/<subscription-id>/resourceGroups/<your-rg>/providers/Microsoft.Compute/galleries/<your-gallery-name>"}
developer_settings:
# Locks will not be added to stateful resources so they can be easily removed
# stateful_resources_locked: false

# If you want to use TRE_URL to point to your local TRE API instance,
# uncomment and set this variable
#   tre_url: __CHANGE_ME__

# This setting will enable your local machine to be able to
# communicate with Service Bus and Cosmos. It will also allow deploying
# the base workspace.
#  enable_local_debugging: true

# Used by the API and Resource processor application to change log level
#  debug: true
